name: Single Runner
on:
    workflow_dispatch:
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: Runner
              run: |
              sudo apt update -y
              sudo apt install openssl
